SOF-1946: Setup WebSocket event api
tv2/inews-gateway pull request #5
Opened 2024-07-10 07:32 UTC by KvelaGorrrrnio

The PR is based on (and supersedes) #4, but is changed to a WebSocket-based event API. Clients can specify in the connection URL (on port 3008) with query parameters which queues to subscribe to. E.g. `ws://inews-gateway:3008?queues=MY.TEST.QUEUE,ANOTHER.TEST.QUEUE` subscribes to the two queues `MY.TEST.QUEUE` and `ANOTHER.TEST.QUEUE`.

For demo purposes, the application is set to emit a test event to all connected clients for each queue they subscribe to every  5 seconds.

I have named the collection of queues that clients subscribe to a _queue pool_ – name suggestions are welcome.

The functionality for handling the client connections is dealt with by the `WebsocketServer` class that implements the `ClientConnectionServer` interface, such that it is easy to swap it out with e.g. SocketIO or raw TCP.

The logic that handles the aggregation of subscriptions on queues by clients is placed in the `IngestEventServer`.

Note that the Node version is fixed at version 22 or above. Set operations from node version 22 are used for the tests.

2024-07-10 15:07 UTC, MadsThy reviewed
Mostly some questions for clarification :)

2024-07-10 15:07 UTC, MadsThy commented on src/presentation/emitters/ingest-event-service.ts
> +  }
```suggestion
  public static getInstance(ingestEventBuilder: IngestEventBuilder): IngestEventService {
    return this.instance ??= new IngestEventService(ingestEventBuilder)
  }
```

2024-07-10 15:07 UTC, MadsThy commented on src/presentation/emitters/ingest-event-service.ts
> +  }
```suggestion
  public emitTestEvent(queueId: string): void {
    this.emitIngestEvent(this.ingestEventBuilder.buildTestEvent(queueId))
  }
```

Is it the norm that we define new variables before using them once only? :) I don't think anyone is in doubt here that is an even that is being built and then emitted 😄

2024-07-10 15:07 UTC, MadsThy commented on src/presentation/emitters/queue-pool-observer.ts
> +  }
```suggestion
  public static getInstance(): QueuePoolObserver {
    return this.instance ??= new QueuePoolObserver()
  }
```

2024-07-10 15:07 UTC, MadsThy commented on src/presentation/services/ingest-event-server.ts
> +    logger: Logger,
Aren't you missing an accessibility modifier here? :)
```suggestion
    private readonly logger: Logger,
```

2024-07-11 10:38 UTC, LindvedKrvang requested changes
This took me quite a while to understand what was going on. I think the main reason for that is:
- The `QueuePoolObserver` does some functionality that is out-of-scope of the task, but also most likely is not necesseary. (You are using it for a behaviour that we don't need in production.)
- `IngestEventServer` and `ClientConnectionServer` shares the same responsibility and only one should be there.

While reading this I kept getting the feeling of overengineering.

2024-07-11 10:38 UTC, LindvedKrvang commented on src/presentation/emitters/queue-pool-observer.ts
> +export class QueuePoolObserver {
This class confuses me and I don't really see the need for it.
It seems like something that isn't needed untill we actuallly start listening for changes from iNews, which is out of scope for this task, so this is YAGNI.

The current implementation of it reflects your need for sending test events for each queue registered, hence the `emitQueuePool` method, but in practice we won't be emitting the queue pool. We will be emiting ingestEvent.

Since this is out of scope of the task, I would say this should be deleted again.

2024-07-11 10:38 UTC, LindvedKrvang commented on src/presentation/interfaces/client-connection-server.ts
> +export interface ClientConnectionServer {
This interface has the same responsibility as the `IngenstEventServer` and it feels like an unnecessary extra step.

2024-07-11 10:38 UTC, LindvedKrvang commented on src/presentation/services/ingest-event-server.spec.ts
> +interface ClientConnectionServerMock extends ClientConnectionServer {
You shouldn't be creating "Mock" interfaces. When you want a mock of something you use the mocking library to create the mock.
The reason you have to create your own interfaces like this is because you want behaviour that's _not in the current interface_ i.e. you need a _different_ interface. This should be an indication of something being done incorrectly.

2024-07-11 10:38 UTC, LindvedKrvang commented on src/presentation/services/ingest-event-server.spec.ts
> +describe(IngestEventServer.name, () => {
All the tests in here are intergration tests.
But you are kinda forced to do intergration tests because you have split the same responsibility between two classes (`IngestEventServer` and `ClientConnectionServer`). This should indicate that something is not as it should be.

2024-07-12 07:50 UTC, KvelaGorrrrnio commented on src/presentation/interfaces/client-connection-server.ts
> +export interface ClientConnectionServer {
This is kept as from our talk. I have renamed to `sendTo` method to `sendMessageToClient`.
For clarification: The ClientConnectionServers responsibility is to manage the chosen transport implementation (e.g. WebSocket, raw TCP socket or something else), while the IngestEventServer's responsibility is to aggregate and mediate the data from/to the connected clients.

2024-07-12 07:51 UTC, KvelaGorrrrnio commented on src/presentation/services/ingest-event-server.spec.ts
> +interface ClientConnectionServerMock extends ClientConnectionServer {
There are no longer any observable outcomes from the IngestEventServer, since the QueuePoolObserver is removed, so the tests are also removed.

2024-07-12 07:52 UTC, KvelaGorrrrnio commented on src/presentation/services/ingest-event-server.spec.ts
> +describe(IngestEventServer.name, () => {
Tests have been removed.

2024-07-12 07:53 UTC, KvelaGorrrrnio commented on package.json
> +  },
I agree with you that they can be annoying, but can also ensure that code works. They should only be used when necessary. In this case I used features introduced in node 22, so the version requirement was necessary.

2024-07-12 07:56 UTC, KvelaGorrrrnio commented on src/presentation/emitters/ingest-event-service.ts
> +  }
That depends on the use case. If the variable is created to easen the understanding of the value yes (e.g. a complex regular expression), otherwise no. I have inlined the event building.

2024-07-12 07:58 UTC, KvelaGorrrrnio commented on src/presentation/services/ingest-event-server.ts
> +    logger: Logger,
The class member `logger` is defined above the constructor as `private readonly`. The reason it is done this way, is so that we can create a logging context for the logger, where the class name is added as metadata (the `logger.tag(this.constructor.name)` part).

2024-07-15 05:36 UTC, LindvedKrvang commented on src/presentation/services/ingest-event-server.spec.ts
> +interface ClientConnectionServerMock extends ClientConnectionServer {
Even if the QueuePoolObserver wasn't removed, you still shouldn't write mock interfaces like this

2024-07-15 05:40 UTC, LindvedKrvang approved these changes

2024-07-15 05:40 UTC, LindvedKrvang commented on src/logger/dummy-logger.ts
> +export class DummyLogger extends LoggerBase implements Logger {
Do we need a DummyLogger???

2024-07-15 10:22 UTC, KvelaGorrrrnio commented on src/logger/dummy-logger.ts
> +export class DummyLogger extends LoggerBase implements Logger {
Not at the moment. I also noticed it this morning and removed it.

2024-07-16 10:29 UTC, KvelaGorrrrnio commented
@aardhuis Thanks for the suggestion! It looks interesting, both for code generation and for documenting the API.
I don't think I will spend time on in it for this PR, but I think it is worth looking into, so we can bring it up in the team for discussion :)

2024-07-17 05:33 UTC, merged